######################################################################
# Automatically generated by qmake (2.01a) to 1. feb 13:50:49 2007
######################################################################

TEMPLATE = app
TARGET = server
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h \
    tcpthread.h
SOURCES += main.cpp server.cpp \
    tcpthread.cpp
QT += network 
QT += core gui
CONFIG += console
